default: &default
  adapter: postgresql
  encoding: unicode
  pool: 30
  port: <%= ENV["POSTGRES_PORT"] || 5432 %>

development:
  <<: *default
  database: hackday_development

test:
  <<: *default
  database: hackday_test

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
